"use client";

import React, { useEffect, useState, useRef } from "react";
import { motion, useInView } from "framer-motion";
import { Badge } from "@/components/ui/badge";

interface StatItemProps {
  value: number;
  suffix: string;
  label: string;
  description: string;
  duration?: number;
}

function AnimatedCounter({ value, suffix, label, description, duration = 2 }: StatItemProps) {
  const [count, setCount] = useState(0);
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  useEffect(() => {
    if (!isInView) return;

    let start = 0;
    const end = value;
    if (start === end) return;

    const totalMiliseconds = duration * 1000;
    const incrementTime = Math.max(Math.floor(totalMiliseconds / end), 16); // cap at ~60fps
    
    const timer = setInterval(() => {
      start += Math.ceil(end / (totalMiliseconds / incrementTime));
      if (start >= end) {
        clearInterval(timer);
        setCount(end);
      } else {
        setCount(start);
      }
    }, incrementTime);

    return () => clearInterval(timer);
  }, [isInView, value, duration]);

  return (
    <div ref={ref} className="text-center space-y-2 p-6 rounded-xl border border-glass-border bg-surface-50/20 backdrop-blur-xs shadow-elevated hover:bg-surface-50/30 transition-colors">
      <h3 className="text-4xl sm:text-5xl font-extrabold text-text-primary tracking-tight font-mono">
        <motion.span>{count}</motion.span>
        <span className="text-brand-400">{suffix}</span>
      </h3>
      <div className="space-y-1">
        <p className="font-bold text-xs uppercase tracking-wider text-text-primary">{label}</p>
        <p className="text-[11px] text-text-secondary leading-normal">{description}</p>
      </div>
    </div>
  );
}

export function Stats() {
  return (
    <section className="py-20 max-w-5xl mx-auto px-6 relative z-10 select-none">
      <div className="text-center space-y-3.5 mb-16">
        <Badge variant="gradient" className="font-extrabold px-3 py-1 text-xs">Creator Quotas</Badge>
        <h2 className="text-3xl md:text-4xl font-extrabold text-text-primary tracking-tight">
          By Creators, For <span className="gradient-text">Massive Scale</span>
        </h2>
        <p className="max-w-md mx-auto text-sm text-text-secondary">
          Our engines are loaded daily to churn out high-performing metrics for local content.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <AnimatedCounter
          value={15}
          suffix="M+"
          label="Impressions Generated"
          description="Total post views generated by user hooks and caption structures."
        />
        <AnimatedCounter
          value={12}
          suffix="K+"
          label="Hours Saved"
          description="Time saved by automating raw scripting, prompts and captions."
        />
        <AnimatedCounter
          value={45}
          suffix="%"
          label="Avg CTR Boost"
          description="Average CTR growth reported on YouTube thumbnails and hooks."
        />
      </div>
    </section>
  );
}
